(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["components/input-number/index.zh-CN.md"],{

/***/ "./node_modules/bisheng/lib/loaders/source-loader.js!./components/input-number/index.zh-CN.md":
/*!****************************************************************************************************!*\
  !*** ./node_modules/bisheng/lib/loaders/source-loader.js!./components/input-number/index.zh-CN.md ***!
  \****************************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = {
  "content": [
    "section",
    [
      "p",
      "用于选中或输入时间，仅允许输入标准的数字值，可定义范围。"
    ]
  ],
  "meta": {
    "category": "Components",
    "subtitle": "计数器",
    "type": "数据录入",
    "title": "InputNumber",
    "filename": "components/input-number/index.zh-CN.md"
  },
  "toc": [
    "ul",
    [
      "li",
      [
        "a",
        {
          "className": "bisheng-toc-h2",
          "href": "#API",
          "title": "API"
        },
        "API"
      ]
    ],
    [
      "li",
      [
        "a",
        {
          "className": "bisheng-toc-h2",
          "href": "#方法",
          "title": "方法"
        },
        "方法"
      ]
    ]
  ],
  "api": [
    "section",
    [
      "h2",
      "API"
    ],
    [
      "p",
      "属性如下"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "成员"
          ],
          [
            "th",
            "说明"
          ],
          [
            "th",
            "类型"
          ],
          [
            "th",
            "默认值"
          ],
          [
            "th",
            "版本"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "autoFocus"
          ],
          [
            "td",
            "自动获取焦点"
          ],
          [
            "td",
            "boolean"
          ],
          [
            "td",
            "false"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "defaultValue"
          ],
          [
            "td",
            "初始值"
          ],
          [
            "td",
            "number"
          ],
          [
            "td"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "disabled"
          ],
          [
            "td",
            "禁用"
          ],
          [
            "td",
            "boolean"
          ],
          [
            "td",
            "false"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "formatter"
          ],
          [
            "td",
            "指定输入框展示值的格式"
          ],
          [
            "td",
            "function(value: number ",
            "|",
            " string): string"
          ],
          [
            "td",
            "-"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "max"
          ],
          [
            "td",
            "最大值"
          ],
          [
            "td",
            "number"
          ],
          [
            "td",
            "Infinity"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "min"
          ],
          [
            "td",
            "最小值"
          ],
          [
            "td",
            "number"
          ],
          [
            "td",
            "-Infinity"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "parser"
          ],
          [
            "td",
            "指定从 formatter 里转换回数字的方式，和 formatter 搭配使用"
          ],
          [
            "td",
            "function( string): number"
          ],
          [
            "td",
            "-"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "precision"
          ],
          [
            "td",
            "数值精度"
          ],
          [
            "td",
            "number"
          ],
          [
            "td",
            "-"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "decimalSeparator"
          ],
          [
            "td",
            "小数点"
          ],
          [
            "td",
            "string"
          ],
          [
            "td",
            "-"
          ],
          [
            "td",
            "3.10.0"
          ]
        ],
        [
          "tr",
          [
            "td",
            "size"
          ],
          [
            "td",
            "输入框大小"
          ],
          [
            "td",
            "string"
          ],
          [
            "td",
            "无"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "step"
          ],
          [
            "td",
            "每次改变步数，可以为小数"
          ],
          [
            "td",
            "number",
            "|",
            "string"
          ],
          [
            "td",
            "1"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "value"
          ],
          [
            "td",
            "当前值"
          ],
          [
            "td",
            "number"
          ],
          [
            "td"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onChange"
          ],
          [
            "td",
            "变化回调"
          ],
          [
            "td",
            "Function(value: number ",
            "|",
            " string)"
          ],
          [
            "td"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onPressEnter"
          ],
          [
            "td",
            "按下回车的回调"
          ],
          [
            "td",
            "function(e)"
          ],
          [
            "td"
          ],
          [
            "td"
          ]
        ]
      ]
    ],
    [
      "h2",
      "方法"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "名称"
          ],
          [
            "th",
            "描述"
          ],
          [
            "th",
            "版本"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "blur()"
          ],
          [
            "td",
            "移除焦点"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "focus()"
          ],
          [
            "td",
            "获取焦点"
          ],
          [
            "td"
          ]
        ]
      ]
    ]
  ]
};

/***/ })

}]);
//# sourceMappingURL=index.zh-CN.md.js.map