(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["components/alert/index.zh-CN.md"],{

/***/ "./node_modules/bisheng/lib/loaders/source-loader.js!./components/alert/index.zh-CN.md":
/*!*********************************************************************************************!*\
  !*** ./node_modules/bisheng/lib/loaders/source-loader.js!./components/alert/index.zh-CN.md ***!
  \*********************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = {
  "content": [
    "section",
    [
      "p",
      "在页面中显示重要的警告提示信息，显示在页面顶部或底部，需要手动关闭。"
    ]
  ],
  "meta": {
    "category": "Components",
    "subtitle": "警告提示",
    "type": "反馈",
    "title": "Alert",
    "filename": "components/alert/index.zh-CN.md"
  },
  "toc": [
    "ul",
    [
      "li",
      [
        "a",
        {
          "className": "bisheng-toc-h2",
          "href": "#API",
          "title": "API"
        },
        "API"
      ]
    ]
  ],
  "api": [
    "section",
    [
      "h2",
      "API"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "参数"
          ],
          [
            "th",
            "说明"
          ],
          [
            "th",
            "类型"
          ],
          [
            "th",
            "默认值"
          ],
          [
            "th",
            "版本"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "afterClose"
          ],
          [
            "td",
            "关闭动画结束后触发的回调函数"
          ],
          [
            "td",
            "() => void"
          ],
          [
            "td",
            "-"
          ],
          [
            "td",
            "3.3.1"
          ]
        ],
        [
          "tr",
          [
            "td",
            "banner"
          ],
          [
            "td",
            "是否用作顶部公告"
          ],
          [
            "td",
            "boolean"
          ],
          [
            "td",
            "false"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "closable"
          ],
          [
            "td",
            "默认不显示关闭按钮"
          ],
          [
            "td",
            "boolean"
          ],
          [
            "td",
            "无"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "closeText"
          ],
          [
            "td",
            "自定义关闭按钮"
          ],
          [
            "td",
            "string",
            "|",
            "ReactNode"
          ],
          [
            "td",
            "无"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "description"
          ],
          [
            "td",
            "警告提示的辅助性文字介绍"
          ],
          [
            "td",
            "string",
            "|",
            "ReactNode"
          ],
          [
            "td",
            "无"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "icon"
          ],
          [
            "td",
            "自定义图标，",
            [
              "code",
              "showIcon"
            ],
            " 为 ",
            [
              "code",
              "true"
            ],
            " 时有效"
          ],
          [
            "td",
            "ReactNode"
          ],
          [
            "td",
            "-"
          ],
          [
            "td",
            "3.10.0"
          ]
        ],
        [
          "tr",
          [
            "td",
            "message"
          ],
          [
            "td",
            "警告提示内容"
          ],
          [
            "td",
            "string",
            "|",
            "ReactNode"
          ],
          [
            "td",
            "无"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "showIcon"
          ],
          [
            "td",
            "是否显示辅助图标"
          ],
          [
            "td",
            "boolean"
          ],
          [
            "td",
            "false，",
            [
              "code",
              "banner"
            ],
            " 模式下默认值为 true"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "type"
          ],
          [
            "td",
            "指定警告提示的样式，有四种选择 ",
            [
              "code",
              "success"
            ],
            "、",
            [
              "code",
              "info"
            ],
            "、",
            [
              "code",
              "warning"
            ],
            "、",
            [
              "code",
              "error"
            ]
          ],
          [
            "td",
            "string"
          ],
          [
            "td",
            [
              "code",
              "info"
            ],
            "，",
            [
              "code",
              "banner"
            ],
            " 模式下默认值为 ",
            [
              "code",
              "warning"
            ]
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onClose"
          ],
          [
            "td",
            "关闭时触发的回调函数"
          ],
          [
            "td",
            "(e: MouseEvent) => void"
          ],
          [
            "td",
            "无"
          ],
          [
            "td"
          ]
        ]
      ]
    ]
  ]
};

/***/ })

}]);
//# sourceMappingURL=index.zh-CN.md.js.map