(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["components/switch/index.zh-CN.md"],{

/***/ "./node_modules/bisheng/lib/loaders/source-loader.js!./components/switch/index.zh-CN.md":
/*!**********************************************************************************************!*\
  !*** ./node_modules/bisheng/lib/loaders/source-loader.js!./components/switch/index.zh-CN.md ***!
  \**********************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = {
  "content": [
    "section",
    [
      "p",
      "用于两种状态的切换。"
    ]
  ],
  "meta": {
    "category": "Components",
    "subtitle": "开关",
    "type": "数据录入",
    "title": "Switch",
    "filename": "components/switch/index.zh-CN.md"
  },
  "toc": [
    "ul",
    [
      "li",
      [
        "a",
        {
          "className": "bisheng-toc-h2",
          "href": "#API",
          "title": "API"
        },
        "API"
      ]
    ],
    [
      "li",
      [
        "a",
        {
          "className": "bisheng-toc-h2",
          "href": "#自有-API",
          "title": "自有 API"
        },
        "自有 API"
      ]
    ],
    [
      "li",
      [
        "a",
        {
          "className": "bisheng-toc-h2",
          "href": "#方法",
          "title": "方法"
        },
        "方法"
      ]
    ]
  ],
  "api": [
    "section",
    [
      "h2",
      "API"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "参数"
          ],
          [
            "th",
            "说明"
          ],
          [
            "th",
            "类型"
          ],
          [
            "th",
            "默认值"
          ],
          [
            "th",
            "版本"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "autoFocus"
          ],
          [
            "td",
            "组件自动获取焦点"
          ],
          [
            "td",
            "boolean"
          ],
          [
            "td",
            "false"
          ],
          [
            "td",
            "3.2.2"
          ]
        ],
        [
          "tr",
          [
            "td",
            "checked"
          ],
          [
            "td",
            "指定当前是否选中"
          ],
          [
            "td",
            "boolean"
          ],
          [
            "td",
            "false"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "checkedChildren"
          ],
          [
            "td",
            "选中时的内容"
          ],
          [
            "td",
            "string",
            "|",
            "ReactNode"
          ],
          [
            "td"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "defaultChecked"
          ],
          [
            "td",
            "初始是否选中"
          ],
          [
            "td",
            "boolean"
          ],
          [
            "td",
            "false"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "disabled"
          ],
          [
            "td",
            "是否禁用"
          ],
          [
            "td",
            "boolean"
          ],
          [
            "td",
            "false"
          ],
          [
            "td",
            "3.2.2"
          ]
        ],
        [
          "tr",
          [
            "td",
            "loading"
          ],
          [
            "td",
            "加载中的开关"
          ],
          [
            "td",
            "boolean"
          ],
          [
            "td",
            "false"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "size"
          ],
          [
            "td",
            "开关大小，可选值：",
            [
              "code",
              "default"
            ],
            " ",
            [
              "code",
              "small"
            ]
          ],
          [
            "td",
            "string"
          ],
          [
            "td",
            "default"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "unCheckedChildren"
          ],
          [
            "td",
            "非选中时的内容"
          ],
          [
            "td",
            "string",
            "|",
            "ReactNode"
          ],
          [
            "td"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onChange"
          ],
          [
            "td",
            "变化时回调函数"
          ],
          [
            "td",
            "Function(checked: boolean, event: Event)"
          ],
          [
            "td"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onClick"
          ],
          [
            "td",
            "点击时回调函数"
          ],
          [
            "td",
            "Function(checked: boolean, event: Event)"
          ],
          [
            "td"
          ],
          [
            "td",
            "3.13.0"
          ]
        ],
        [
          "tr",
          [
            "td",
            "className"
          ],
          [
            "td",
            "Switch 器类名"
          ],
          [
            "td",
            "string"
          ],
          [
            "td",
            "-"
          ],
          [
            "td",
            "3.10.1"
          ]
        ]
      ]
    ],
    [
      "h2",
      "自有 API"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "参数"
          ],
          [
            "th",
            "说明"
          ],
          [
            "th",
            "类型"
          ],
          [
            "th",
            "默认值"
          ],
          [
            "th",
            "版本"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "activeText"
          ],
          [
            "td",
            "开启状态的提示文案"
          ],
          [
            "td",
            "string"
          ],
          [
            "td",
            "默认值：-"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "inactiveText"
          ],
          [
            "td",
            "关闭状态的提示文案"
          ],
          [
            "td",
            "string"
          ],
          [
            "td",
            "默认值：-"
          ],
          [
            "td"
          ]
        ]
      ]
    ],
    [
      "h2",
      "方法"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "名称"
          ],
          [
            "th",
            "描述"
          ],
          [
            "th",
            "版本"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "blur()"
          ],
          [
            "td",
            "移除焦点"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "focus()"
          ],
          [
            "td",
            "获取焦点"
          ],
          [
            "td"
          ]
        ]
      ]
    ]
  ]
};

/***/ })

}]);
//# sourceMappingURL=index.zh-CN.md.js.map