(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["components/tabs/index.zh-CN.md"],{

/***/ "./node_modules/bisheng/lib/loaders/source-loader.js!./components/tabs/index.zh-CN.md":
/*!********************************************************************************************!*\
  !*** ./node_modules/bisheng/lib/loaders/source-loader.js!./components/tabs/index.zh-CN.md ***!
  \********************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = {
  "content": [
    "section",
    [
      "p",
      "在页面上提供平级内容区域的切换展示。"
    ]
  ],
  "meta": {
    "category": "Components",
    "subtitle": "标签页",
    "type": "数据展示",
    "title": "Tabs",
    "cols": 1,
    "filename": "components/tabs/index.zh-CN.md"
  },
  "toc": [
    "ul",
    [
      "li",
      [
        "a",
        {
          "className": "bisheng-toc-h2",
          "href": "#API",
          "title": "API"
        },
        "API"
      ]
    ]
  ],
  "api": [
    "section",
    [
      "h2",
      "API"
    ],
    [
      "h3",
      "Tabs"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "参数"
          ],
          [
            "th",
            "说明"
          ],
          [
            "th",
            "类型"
          ],
          [
            "th",
            "默认值"
          ],
          [
            "th",
            "版本"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "activeKey"
          ],
          [
            "td",
            "当前激活 tab 面板的 key"
          ],
          [
            "td",
            "string"
          ],
          [
            "td",
            "无"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "animated"
          ],
          [
            "td",
            "是否使用动画切换 Tabs，在 ",
            [
              "code",
              "tabPosition=top|bottom"
            ],
            " 时有效"
          ],
          [
            "td",
            "boolean ",
            "|",
            " {inkBar:boolean, tabPane:boolean}"
          ],
          [
            "td",
            "true, 当 type=\"card\" 时为 false"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "renderTabBar"
          ],
          [
            "td",
            "替换 TabBar，用于二次封装标签头"
          ],
          [
            "td",
            "(props: DefaultTabBarProps, DefaultTabBar: React.ComponentClass) => React.ReactElement"
          ],
          [
            "td",
            "无"
          ],
          [
            "td",
            "3.9.0"
          ]
        ],
        [
          "tr",
          [
            "td",
            "defaultActiveKey"
          ],
          [
            "td",
            "初始化选中面板的 key，如果没有设置 activeKey"
          ],
          [
            "td",
            "string"
          ],
          [
            "td",
            "第一个面板"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "hideAdd"
          ],
          [
            "td",
            "是否隐藏加号图标，在 ",
            [
              "code",
              "type=\"editable-card\""
            ],
            " 时有效"
          ],
          [
            "td",
            "boolean"
          ],
          [
            "td",
            "false"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "size"
          ],
          [
            "td",
            "大小，提供 ",
            [
              "code",
              "large"
            ],
            " ",
            [
              "code",
              "default"
            ],
            " 和 ",
            [
              "code",
              "small"
            ],
            " 三种大小"
          ],
          [
            "td",
            "string"
          ],
          [
            "td",
            "'default'"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "tabBarExtraContent"
          ],
          [
            "td",
            "tab bar 上额外的元素"
          ],
          [
            "td",
            "React.ReactNode"
          ],
          [
            "td",
            "无"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "tabBarGutter"
          ],
          [
            "td",
            "tabs 之间的间隙"
          ],
          [
            "td",
            "number"
          ],
          [
            "td",
            "无"
          ],
          [
            "td",
            "3.2.0"
          ]
        ],
        [
          "tr",
          [
            "td",
            "tabBarStyle"
          ],
          [
            "td",
            "tab bar 的样式对象"
          ],
          [
            "td",
            "object"
          ],
          [
            "td",
            "-"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "tabPosition"
          ],
          [
            "td",
            "页签位置，可选值有 ",
            [
              "code",
              "top"
            ],
            " ",
            [
              "code",
              "right"
            ],
            " ",
            [
              "code",
              "bottom"
            ],
            " ",
            [
              "code",
              "left"
            ]
          ],
          [
            "td",
            "string"
          ],
          [
            "td",
            "'top'"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "type"
          ],
          [
            "td",
            "页签的基本样式，可选 ",
            [
              "code",
              "line"
            ],
            "、",
            [
              "code",
              "card"
            ],
            " ",
            [
              "code",
              "editable-card"
            ],
            " 类型"
          ],
          [
            "td",
            "string"
          ],
          [
            "td",
            "'line'"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onChange"
          ],
          [
            "td",
            "切换面板的回调"
          ],
          [
            "td",
            "Function(activeKey) {}"
          ],
          [
            "td",
            "无"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onEdit"
          ],
          [
            "td",
            "新增和删除页签的回调，在 ",
            [
              "code",
              "type=\"editable-card\""
            ],
            " 时有效"
          ],
          [
            "td",
            "(targetKey, action): void"
          ],
          [
            "td",
            "无"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onNextClick"
          ],
          [
            "td",
            "next 按钮被点击的回调"
          ],
          [
            "td",
            "Function"
          ],
          [
            "td",
            "无"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onPrevClick"
          ],
          [
            "td",
            "prev 按钮被点击的回调"
          ],
          [
            "td",
            "Function"
          ],
          [
            "td",
            "无"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onTabClick"
          ],
          [
            "td",
            "tab 被点击的回调"
          ],
          [
            "td",
            "Function"
          ],
          [
            "td",
            "无"
          ],
          [
            "td"
          ]
        ]
      ]
    ],
    [
      "h3",
      "Tabs.TabPane"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "参数"
          ],
          [
            "th",
            "说明"
          ],
          [
            "th",
            "类型"
          ],
          [
            "th",
            "默认值"
          ],
          [
            "th",
            "版本"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "forceRender"
          ],
          [
            "td",
            "被隐藏时是否渲染 DOM 结构"
          ],
          [
            "td",
            "boolean"
          ],
          [
            "td",
            "false"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "key"
          ],
          [
            "td",
            "对应 activeKey"
          ],
          [
            "td",
            "string"
          ],
          [
            "td",
            "无"
          ],
          [
            "td"
          ]
        ],
        [
          "tr",
          [
            "td",
            "tab"
          ],
          [
            "td",
            "选项卡头显示文字"
          ],
          [
            "td",
            "string",
            "|",
            "ReactNode"
          ],
          [
            "td",
            "无"
          ],
          [
            "td"
          ]
        ]
      ]
    ]
  ]
};

/***/ })

}]);
//# sourceMappingURL=index.zh-CN.md.js.map