(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["components/checkbox/index.zh-CN.md"],{

/***/ "./node_modules/bisheng/lib/loaders/source-loader.js!./components/checkbox/index.zh-CN.md":
/*!************************************************************************************************!*\
  !*** ./node_modules/bisheng/lib/loaders/source-loader.js!./components/checkbox/index.zh-CN.md ***!
  \************************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = {
  "content": [
    "section",
    [
      "p",
      "一组备选项中进行多选"
    ]
  ],
  "meta": {
    "category": "Components",
    "subtitle": "多选框",
    "type": "数据录入",
    "title": "Checkbox",
    "filename": "components/checkbox/index.zh-CN.md"
  },
  "toc": [
    "ul",
    [
      "li",
      [
        "a",
        {
          "className": "bisheng-toc-h2",
          "href": "#API",
          "title": "API"
        },
        "API"
      ]
    ]
  ],
  "api": [
    "section",
    [
      "h2",
      "API"
    ],
    [
      "h3",
      "属性"
    ],
    [
      "h4",
      "Checkbox"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "参数"
          ],
          [
            "th",
            "说明"
          ],
          [
            "th",
            "类型"
          ],
          [
            "th",
            "默认值"
          ],
          [
            "th",
            "版本"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "autoFocus"
          ],
          [
            "td",
            "自动获取焦点"
          ],
          [
            "td",
            "boolean"
          ],
          [
            "td",
            "false"
          ],
          [
            "td",
            "3.6.2"
          ]
        ],
        [
          "tr",
          [
            "td",
            "checked"
          ],
          [
            "td",
            "指定当前是否选中"
          ],
          [
            "td",
            "boolean"
          ],
          [
            "td",
            "false"
          ],
          [
            "td",
            "3.6.2"
          ]
        ],
        [
          "tr",
          [
            "td",
            "defaultChecked"
          ],
          [
            "td",
            "初始是否选中"
          ],
          [
            "td",
            "boolean"
          ],
          [
            "td",
            "false"
          ],
          [
            "td",
            "3.6.2"
          ]
        ],
        [
          "tr",
          [
            "td",
            "disabled"
          ],
          [
            "td",
            "失效状态"
          ],
          [
            "td",
            "boolean"
          ],
          [
            "td",
            "false"
          ],
          [
            "td",
            "3.6.2"
          ]
        ],
        [
          "tr",
          [
            "td",
            "indeterminate"
          ],
          [
            "td",
            "设置 indeterminate 状态，只负责样式控制"
          ],
          [
            "td",
            "boolean"
          ],
          [
            "td",
            "false"
          ],
          [
            "td",
            "3.6.2"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onChange"
          ],
          [
            "td",
            "变化时回调函数"
          ],
          [
            "td",
            "Function(e:Event)"
          ],
          [
            "td",
            "-"
          ],
          [
            "td",
            "3.6.2"
          ]
        ]
      ]
    ],
    [
      "h4",
      "Checkbox Group"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "参数"
          ],
          [
            "th",
            "说明"
          ],
          [
            "th",
            "类型"
          ],
          [
            "th",
            "默认值"
          ],
          [
            "th",
            "版本"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "defaultValue"
          ],
          [
            "td",
            "默认选中的选项"
          ],
          [
            "td",
            "string",
            "[",
            "]"
          ],
          [
            "td",
            "[",
            "]"
          ],
          [
            "td",
            "3.6.2"
          ]
        ],
        [
          "tr",
          [
            "td",
            "disabled"
          ],
          [
            "td",
            "整组失效"
          ],
          [
            "td",
            "boolean"
          ],
          [
            "td",
            "false"
          ],
          [
            "td",
            "3.6.2"
          ]
        ],
        [
          "tr",
          [
            "td",
            "name"
          ],
          [
            "td",
            "CheckboxGroup 下所有 ",
            [
              "code",
              "input[type=\"checkbox\"]"
            ],
            " 的 ",
            [
              "code",
              "name"
            ],
            " 属性"
          ],
          [
            "td",
            "string"
          ],
          [
            "td",
            "-"
          ],
          [
            "td",
            "3.16.0"
          ]
        ],
        [
          "tr",
          [
            "td",
            "options"
          ],
          [
            "td",
            "指定可选项"
          ],
          [
            "td",
            "string",
            "[",
            "] ",
            "|",
            " Option",
            "[",
            "]"
          ],
          [
            "td",
            "[",
            "]"
          ],
          [
            "td",
            "3.6.2"
          ]
        ],
        [
          "tr",
          [
            "td",
            "value"
          ],
          [
            "td",
            "指定选中的选项"
          ],
          [
            "td",
            "string",
            "[",
            "]"
          ],
          [
            "td",
            "[",
            "]"
          ],
          [
            "td",
            "3.6.2"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onChange"
          ],
          [
            "td",
            "变化时回调函数"
          ],
          [
            "td",
            "Function(checkedValue)"
          ],
          [
            "td",
            "-"
          ],
          [
            "td",
            "3.6.2"
          ]
        ]
      ]
    ],
    [
      "h5",
      "Option"
    ],
    [
      "pre",
      {
        "lang": "typescript",
        "highlighted": "<span class=\"token keyword\">interface</span> <span class=\"token class-name\">Option</span> <span class=\"token punctuation\">{</span>\n  label<span class=\"token punctuation\">:</span> <span class=\"token keyword\">string</span><span class=\"token punctuation\">;</span>\n  value<span class=\"token punctuation\">:</span> <span class=\"token keyword\">string</span><span class=\"token punctuation\">;</span>\n  disabled<span class=\"token operator\">?</span><span class=\"token punctuation\">:</span> <span class=\"token keyword\">boolean</span><span class=\"token punctuation\">;</span>\n<span class=\"token punctuation\">}</span>"
      },
      [
        "code",
        "interface Option {\n  label: string;\n  value: string;\n  disabled?: boolean;\n}"
      ]
    ],
    [
      "h3",
      "方法"
    ],
    [
      "h4",
      "Checkbox"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "名称"
          ],
          [
            "th",
            "描述"
          ],
          [
            "th",
            "版本"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "blur()"
          ],
          [
            "td",
            "移除焦点"
          ],
          [
            "td",
            "3.6.2"
          ]
        ],
        [
          "tr",
          [
            "td",
            "focus()"
          ],
          [
            "td",
            "获取焦点"
          ],
          [
            "td",
            "3.6.2"
          ]
        ]
      ]
    ]
  ]
};

/***/ })

}]);
//# sourceMappingURL=index.zh-CN.md.js.map